films/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from films import settings
from movies import views

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    # path('', )
    path("", include("movies.urls")),
    path("profile/", TemplateView.as_view(template_name="profile/user.html"), name="profile"),
    path("profile/favourites/", views.FavoritesListView.as_view(template_name="profile/favourites_list.html"), name="favorite"),
]) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.MainMoviesView.as_view(), name="home"),
    path("movies/", views.MoviesView.as_view(), name="movies"),
    path("movies/filter/", views.FilterMoviesView.as_view(), name="filter"),
    path("movies/add-rating/", views.AddStarRating.as_view(), name="add_rating"),
    path("movies/search/", views.Search.as_view(), name="search"),
    path("movies/<slug:slug>/", views.MovieDetailView.as_view(), name="movie_detail"),
    path("movies/<slug:slug>/favourite/", views.FavouriteMovieView.as_view(), name="favourite"),
    path("movies/review/<int:pk>/", views.AddReview.as_view(), name="add_review"),
]

movies/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import date

from django.urls import reverse


class Category(models.Model):
    """Категории"""
    name = models.CharField("Категория", max_length=150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Actor(models.Model):
    """Актеры и режиссеры"""
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="actors/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={"slug": self.name})

    class Meta:
        verbose_name = "Актеры и режиссеры"
        verbose_name_plural = "Актеры и режиссеры"


class Genre(models.Model):
    """Жанры"""
    name = models.CharField("Имя", max_length=100)
    description = models.TextField("Описание", blank=True)
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Movie(models.Model):
    """Фильм"""
    title = models.CharField("Название", max_length=100)
    tagline = models.CharField("Слоган", max_length=200, default='')
    description = models.TextField("Описание")
    poster = models.ImageField("Постер", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Дата выхода", default=2019)
    country = models.CharField("Страна", max_length=350)
    directors = models.ManyToManyField(Actor, verbose_name="режиссер", related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="актеры", related_name="film_actor")
    genres = models.ManyToManyField(Genre, verbose_name="жанры")
    rating = models.FloatField("Рейтинг фильма", default=3.5)
    world_premiere = models.DateField("Примьера в мире", default=date.today)
    budget = models.PositiveIntegerField("Бюджет", default=0,
                                         help_text="указывать сумму в долларах")
    fees_in_usa = models.PositiveIntegerField(
        "Сборы в США", default=0, help_text="указывать сумму в долларах"
    )
    fess_in_world = models.PositiveIntegerField(
        "Сборы в мире", default=0, help_text="указывать сумму в долларах"
    )
    category = models.ForeignKey(
        Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True
    )
    url = models.SlugField(max_length=130, unique=True)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movie_detail", kwargs={"slug": self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    def average_rating(self):
        ratings = self.ratings.all()
        return ratings.aggregate(models.Avg('star'))['star__avg'] or 3.5

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"


class MovieShots(models.Model):
    """Кадры из фильма"""
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Описание", blank=True)
    image = models.ImageField("Изображение", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"


class RatingStar(models.Model):
    """Звезда рейтинга"""
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    """Рейтинг"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="пользователь")
    star = models.SmallIntegerField("Звезда", default=0)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="фильм", related_name="ratings")

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):
    """Отзывы"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="пользователь")
    text = models.TextField("Сообщение", max_length=5000)
    movie = models.ForeignKey(Movie, verbose_name="фильм", on_delete=models.CASCADE)

    # def __str__(self):
    #     return f"{self.user.username} - {self.movie}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"


class Favorites(models.Model):
    """Избранное"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="пользователь")
    movies = models.ManyToManyField(Movie, blank=True)

    def __str__(self):
        return f"{self.user.username}"

    class Meta:
        verbose_name = "Избранное"
        verbose_name_plural = "Избранное"

movies/forms.py
from django import forms

from .models import Reviews, Rating


class ReviewForm(forms.ModelForm):
    """Форма отзывов"""
    class Meta:
        model = Reviews
        fields = ("text",)


class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    class Meta:
        model = Rating
        fields = ("star",)

movies/views.py
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.base import View

from .models import *
from .forms import ReviewForm, RatingForm


class GenreYear:
    """Жанры и года выхода фильмов"""
    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Movie.objects.filter(draft=False).values("year")


class MoviesView(GenreYear, ListView):
    """Список фильмов"""
    model = Movie
    queryset = Movie.objects.filter(draft=False)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["categories"] = Category.objects.all()
        return context


class MovieDetailView(GenreYear, DetailView):
    """Полное описание фильма"""
    model = Movie
    slug_field = "url"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["star_form"] = RatingForm()

        user = self.request.user
        movie = kwargs.get('object')

        if user.id:
            favorite_list, created = Favorites.objects.get_or_create(user=user)

            if favorite_list.movies.filter(id=movie.pk).exists():
                context['is_favourite'] = True
            else:
                context['is_favourite'] = False
        return context


class MainMoviesView(ListView):
    """Сортировка фильмов по рейтингу"""
    template_name = 'home.html'
    model = Movie
    queryset = Movie.objects.filter(draft=False).order_by('-rating')[:30]

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["categories"] = Category.objects.all()
        return context


class FilterMoviesView(GenreYear, ListView):
    """Фильтрация фильмов"""
    def get_queryset(self):
        if self.request.GET.getlist("year"):
            if self.request.GET.getlist("genre"):
                queryset = Movie.objects.filter(
                    Q(year__in=self.request.GET.getlist("year")) &
                    Q(genres__in=self.request.GET.getlist("genre")) &
                    Q(draft = False)
                ).distinct()
            else:
                queryset = Movie.objects.filter(
                    Q(year__in=self.request.GET.getlist("year"))&
                    Q(draft=False)
                ).distinct()
        else:
            if self.request.GET.getlist("genre"):
                queryset = Movie.objects.filter(
                    Q(genres__in=self.request.GET.getlist("genre"))&
                    Q(draft=False)
                ).distinct()

        return queryset


class AddReview(View):
    """Отзывы"""
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.movie_id = pk
            form.user = request.user
            movie = Movie.objects.filter(id=pk).first()
            form.save()
        return HttpResponseRedirect(movie.get_absolute_url())


class Search(ListView):
    """Поиск фильмов"""
    def get_queryset(self):
        return Movie.objects.filter(title__icontains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = self.request.GET.get("q")
        return context


class AddStarRating(View):
    """Добавление рейтинга к фильму"""
    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                user_id=request.POST.get("user"),
                movie_id=request.POST.get("movie"),
                defaults={'star': request.POST.get("star")},
            )
            film = Movie.objects.get(id=request.POST.get("movie"))
            new_rating = film.average_rating()
            film.rating = new_rating
            film.save()

            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)


class FavouriteMovieView(DetailView):
    """Избранное"""
    model = Favorites

    def post(self, request, *args, **kwargs):
        movie = Movie.objects.filter(url=kwargs["slug"]).first()

        favorite_list, created = Favorites.objects.get_or_create(user=request.user)
        if favorite_list.movies.filter(id=movie.pk).exists():
            favorite_list.movies.remove(movie.pk)
        else:
            favorite_list.movies.add(movie.pk)
        favorite_list.save()
        return HttpResponseRedirect(movie.get_absolute_url())


class FavoritesListView(ListView):
    """Список любимых фильмов"""
    model = Favorites
    template_name = 'favorites.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        favorite_list, created = Favorites.objects.get_or_create(user=user)
        context["favourite_movies"] = favorite_list.movies.all()
        return context

templates/movies/base.html
{% extends 'base.html' %}
<div class="container">
    {% block content %}

    {% endblock content %}
</div>

templates/movies/movie_detail.html
{% extends 'movies/base.html' %}
{% load movie_tag %}
    {% block title %}{{movie.title}}{% endblock title %}
    {% block content %}
        <div class="container">
            <div class="card">
              <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{ movie.poster.url }}" alt="{{ movie.title }}">
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                      <h5 class="card-title">{{movie.title}}</h5>
                      {% if user.is_authenticated %}
                          <div id="favorite-block">
                              <form action="{% url 'favourite' movie.url %}" method="post">
                                  {% csrf_token %}
                                  <input type="hidden" name="pk" value="{{ movie.pk }}">
                                  <button type="submit">

                                        {% if is_favourite %}
                                          <i class="fa fa-heart fa-lg"></i>
                                        {% else %}
                                          <i class="fa fa-heart-o fa-lg"></i>
                                        {% endif %}

                                  </button>
                                </form>
                          </div>
                      {% endif %}
                      <p class="card-text"><i>{{movie.tagline}}</i></p>
                      <p class="card-text">{{movie.description}}</p>
                      <div><p><b>Жанр:</b> {{movie.genres.all|join:", "}}</p></div>
                      <div><p><b>Год:</b> {{movie.year}}</p></div>
                      <p class="card-text"><b>Страна:</b> {{movie.country}}</p>
                      <p class="card-text"><b>Режиссер:</b>
                          {% for dir in movie.directors.all %}
                            {{dir.name}}
                          {% endfor %}
                      </p>
                      <p class="card-text"><b>Актеры:</b>
                        {% for dir in movie.actors.all %}
                            {{dir.name}}
                          {% endfor %}
                      </p>
                      <p class="card-text"><b>Премьера в мире:</b> {{movie.world_premiere}}</p>
                      <p class="card-text"><b>Бюджет:</b> ${{movie.budget}}</p>
                      <p class="card-text"><b>Сборы в США:</b> ${{movie.fees_in_usa}}</p>
                      <p class="card-text"><b>Сборы в мире:</b> ${{movie.fess_in_world}}</p>

                       {% with rating_value=movie.rating|stringformat:'d' %}
                            <div class="rating-block">
                               {% if user.is_authenticated %}
                                      <form rate="{{rating_value}}" action="{% url 'add_rating' %}" method="post" name="rating">
                                          <b>Рейтинг:</b>
                                          {% csrf_token %}
                                          <input type="hidden" name="movie" value="{{movie.id}}">
                                          <input type="hidden" name="user" value="{{user.id}}">

                                          <span class="rating">
                                              <input id="rating5" type="radio" name="star" value="5" {% if rating_value == '5' %} checked {% endif %}>
                                              <label for="rating5" >5</label>
                                              <input id="rating4" type="radio" name="star" value="4" {% if rating_value == '4' %} checked {% endif %}>
                                              <label for="rating4" >4</label>
                                              <input id="rating3" type="radio" name="star" value="3" {% if rating_value == '3' %} checked {% endif %}>
                                              <label for="rating3">3</label>
                                              <input id="rating2" type="radio" name="star" value="2" {% if rating_value == '2' %} checked {% endif %}>
                                              <label for="rating2">2</label>
                                              <input id="rating1" type="radio" name="star" value="1" {% if rating_value == '1' %} checked {% endif %}>
                                              <label for="rating1">1</label>
                                          </span>
                                          <span class="editContent">{{ movie.rating|formatted_float:1 }}</span>
                                      </form>
                              {% else %}
                                  <div class="no-vote">
                                      <span class="rating">
                                          <input id="rating5" type="radio" name="star" value="5" {% if rating_value == '5' %} checked {% endif %}>
                                          <label for="rating5" >5</label>
                                          <input id="rating4" type="radio" name="star" value="4" {% if rating_value == '4' %} checked {% endif %}>
                                          <label for="rating4" >4</label>
                                          <input id="rating3" type="radio" name="star" value="3" {% if rating_value == '3' %} checked {% endif %}>
                                          <label for="rating3">3</label>
                                          <input id="rating2" type="radio" name="star" value="2" {% if rating_value == '2' %} checked {% endif %}>
                                          <label for="rating2">2</label>
                                          <input id="rating1" type="radio" name="star" value="1" {% if rating_value == '1' %} checked {% endif %}>
                                          <label for="rating1">1</label>
                                      </span>
                                      <span class="editContent">{{ movie.rating|formatted_float:1 }}</span>
                                  </div>
                              {% endif %}
                            </div>
                      {% endwith %}
                  </div>
                </div>
              </div>
            </div>

            <div class="movie-info">
                <div class="row">
                    {% for shot in movie.movieshots_set.all %}
                        <div class="col-4">
                            <img src="{{ shot.image.url }}" alt="{{ shot.title }}">
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="movie-reviews">
                <h2>Отзывы</h2>
                <div class="movie-comments">
                    {% for review in movie.reviews_set.all %}
                    <div class="comment-item">
                        <div class="item-body">
                            <h5>{{ review.user.username }}</h5>
                            <p class="mt-2">
                                {{ review.text }}
                            </p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% if user.is_authenticated %}
                    <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4">
                        {% csrf_token %}
                        <div class="form-group editContent">
                            <label for="contactcomment" class="editContent">
                                Ваш комментарий *
                            </label>
                            <textarea name="text" class="form-control border" rows="5" id="contactcomment" required=""></textarea>
                        </div>
                        <div class="d-sm-flex">

                            <button type="submit" class="mt-3 btn btn-dark py-3">Отправить</button>
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>
    {% endblock content %}

templates/movies/movie_list.html
{% extends 'movies/base.html' %}
        {% block content %}
            <div class="container">
                <div class="row ">
                    <h1>Список фильмов</h1>
                </div>
                <div class="row ">
                    <div class="col-4">
                        {% include 'include/sidebar.html' %}
                    </div>
                    <div class="col-8">
                        <div class="row">
                            {% for movie in movie_list %}
                                <div class="col-4">
                                    <div class="card">
                                        <a href="/movies/{{ movie.url }}/">
                                            <img src="{{ movie.poster.url }}" alt="{{ movie.title }}" class="card-img-top">
                                            <div class="card-body">
                                                <h5 class="card-title">{{ movie.title }}</h5>
                                                <div>{{ movie.rating|floatformat:1 }}</div>
                                                <div>{{movie.genres.all|join:", "}}</div>
                                                <div>{{ movie.year }}</div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        {% endblock content %}